### ISSUE TITLE
As a visitor, I want to contribute my own recipe, so that the website can be richer in content

### ISSUE THREAD

**Issue by phongvu99** [phongvu99/USTH-SE-2019#2]
Spaghetti and Meatballs!

**Comment by dannguyen99** [comment]
- [ ] Implement an API for importing recipes from external services or files
- [ ] Test the API before deploying it to the site
- [ ] Improve the design based on the feedback
- [ ] Deploy it!

**Comment by phongvu99** [comment]
- [ ] Implement an API for importing recipes from external services or files.
- [ ] Test the API before deploying it to the site.
- [ ] Utilizing the Extreming Programming to constantly improving the design.
- [ ] Deploy it!
