### ISSUE TITLE
Assigning Roles

### ISSUE THREAD

**Issue by phongvu99** [phongvu99/USTH-SE-2019#2]
<h1> Member Roles: </h1>
<ol>
<li> Dan: Front-end, Back-end</li>
<li> Phong:  Captain, Front-end, Back-end</li>
<li> Tung: Front-end</li>
<li> Tuan: Tester </li>
</ol>
Should you need any help, please refer to our Discord server.

**Comment by dannguyen99** [comment]
Day1: I can use bootstrap on my own

**Comment by dannguyen99** [comment]
> Day1: I can use bootstrap on my own

 wtf are u talking about

**Comment by phongvu99** [comment]
Day2: I can create HTML page with CSS implemented on my own

**Comment by phongvu99** [comment]
> 
> 
> Day2: I can create HTML page with CSS implemented on my own

get out of here, m8

**Comment by phongvu99** [comment]
day3: goodbye...
