### ISSUE TITLE
As an Alzheimer, I want to keep track of my progress so that I won't make mistakes

### ISSUE THREAD

**Issue by phongvu99** [phongvu99/USTH-SE-2019#3]
As an Alzheimer, I constantly forget things. So the website will provide me the tools to archive the progression on my culinary journey.
At this point, I forgot why I'm doing this.

**Comment by dannguyen99** [comment]
**Requirements**

- [x] Gets to know the customer
- [x] Gathering information relating to Alzheimer patients

<h3>High-level design</h3>

- [x] Compare with the INVEST guideline.
- [x] Learn basics Javascript, CSS and HTML.
- [x] Learn a front-end framework: Vue, React, Angular,...
<h3> Low-level design</h3>

- [x] Comes up with a design that best suits Alzheimer.
- [x] Discuss the idea with the front-end developers.
- [x] Design automated test-cases for each scenario.
- [x] Refactor the code based on the review.
